"""add tabellone tables

Revision ID: 0daf14e9697d
Revises: d9b66a27204f
Create Date: 2026-06-06 16:33:06.504417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0daf14e9697d'
down_revision: Union[str, Sequence[str], None] = 'd9b66a27204f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_outcomes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('scudetto_team', sa.String(length=80), nullable=True),
    sa.Column('scudetto_points', sa.Integer(), nullable=True),
    sa.Column('relegated_a_1', sa.String(length=80), nullable=True),
    sa.Column('relegated_a_2', sa.String(length=80), nullable=True),
    sa.Column('relegated_a_3', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_a', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_a_goals', sa.Integer(), nullable=True),
    sa.Column('promoted_b_direct_1', sa.String(length=80), nullable=True),
    sa.Column('promoted_b_direct_2', sa.String(length=80), nullable=True),
    sa.Column('promoted_b_first_points', sa.Integer(), nullable=True),
    sa.Column('playoff_b_1', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_2', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_3', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_4', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_5', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_6', sa.String(length=80), nullable=True),
    sa.Column('promoted_b_playoff', sa.String(length=80), nullable=True),
    sa.Column('playoffs_held', sa.Boolean(), nullable=True),
    sa.Column('relegated_b_c_direct_1', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_direct_2', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_direct_3', sa.String(length=80), nullable=True),
    sa.Column('playout_b_1', sa.String(length=80), nullable=True),
    sa.Column('playout_b_2', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_playout', sa.String(length=80), nullable=True),
    sa.Column('playout_held', sa.Boolean(), nullable=True),
    sa.Column('top_scorer_b', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_b_goals', sa.Integer(), nullable=True),
    sa.Column('coppa_italia_winner', sa.String(length=80), nullable=True),
    sa.Column('champions_winner', sa.String(length=80), nullable=True),
    sa.Column('europa_winner', sa.String(length=80), nullable=True),
    sa.Column('conference_winner', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id')
    )
    op.create_table('table_predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('mercato_penalty', sa.Integer(), nullable=False),
    sa.Column('scudetto_team', sa.String(length=80), nullable=True),
    sa.Column('scudetto_points_guess', sa.Integer(), nullable=True),
    sa.Column('relegated_a_1', sa.String(length=80), nullable=True),
    sa.Column('relegated_a_2', sa.String(length=80), nullable=True),
    sa.Column('relegated_a_3', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_a', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_a_goals', sa.Integer(), nullable=True),
    sa.Column('promoted_b_direct_1', sa.String(length=80), nullable=True),
    sa.Column('promoted_b_direct_2', sa.String(length=80), nullable=True),
    sa.Column('promoted_b_first_points', sa.Integer(), nullable=True),
    sa.Column('playoff_b_1', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_2', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_3', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_4', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_5', sa.String(length=80), nullable=True),
    sa.Column('playoff_b_6', sa.String(length=80), nullable=True),
    sa.Column('promoted_b_playoff', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_direct_1', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_direct_2', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_direct_3', sa.String(length=80), nullable=True),
    sa.Column('playout_b_1', sa.String(length=80), nullable=True),
    sa.Column('playout_b_2', sa.String(length=80), nullable=True),
    sa.Column('relegated_b_c_playout', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_b', sa.String(length=80), nullable=True),
    sa.Column('top_scorer_b_goals', sa.Integer(), nullable=True),
    sa.Column('coppa_italia_winner', sa.String(length=80), nullable=True),
    sa.Column('champions_winner', sa.String(length=80), nullable=True),
    sa.Column('europa_winner', sa.String(length=80), nullable=True),
    sa.Column('conference_winner', sa.String(length=80), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', name='uq_tabellone_player_season')
    )
    op.create_table('table_prediction_modifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('penalty_points', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['table_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_prediction_modifications')
    op.drop_table('table_predictions')
    op.drop_table('season_outcomes')
    # ### end Alembic commands ###
