"""add tabellone scoring columns

Revision ID: 2957e62e3181
Revises: 0daf14e9697d
Create Date: 2026-06-06 16:45:52.794606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2957e62e3181'
down_revision: Union[str, Sequence[str], None] = '0daf14e9697d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_predictions', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('table_predictions', sa.Column('points_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('table_predictions', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_predictions', 'scored_at')
    op.drop_column('table_predictions', 'points_breakdown')
    op.drop_column('table_predictions', 'total_points')
    # ### end Alembic commands ###
