"""add rounds matches staged_fixtures

Revision ID: 726952479686
Revises: 2957e62e3181
Create Date: 2026-06-06 17:32:39.506946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726952479686'
down_revision: Union[str, Sequence[str], None] = '2957e62e3181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staged_fixtures',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('api_fixture_id', sa.Integer(), nullable=False),
    sa.Column('competition', sa.Enum('serie_a', 'serie_b', 'champions_league', 'mixed', name='competition'), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('matchday', sa.SmallInteger(), nullable=True),
    sa.Column('home_team', sa.String(length=80), nullable=False),
    sa.Column('away_team', sa.String(length=80), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_to_round', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_fixture_id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('competition', sa.Enum('serie_a', 'serie_b', 'champions_league', 'mixed', name='competition'), nullable=False),
    sa.Column('matchday', sa.SmallInteger(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'completed', name='roundstatus'), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('home_team', sa.String(length=80), nullable=False),
    sa.Column('away_team', sa.String(length=80), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_home_goals', sa.SmallInteger(), nullable=True),
    sa.Column('actual_away_goals', sa.SmallInteger(), nullable=True),
    sa.Column('api_fixture_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('rounds')
    op.drop_table('staged_fixtures')
    # Gli enum non vengono droppati automaticamente: vanno rimossi a mano
    op.execute("DROP TYPE IF EXISTS roundstatus")
    op.execute("DROP TYPE IF EXISTS competition")
    # ### end Alembic commands ###
