"""add player_season_profile

Revision ID: 7ea48c4fe03d
Revises: 8d673165ccf4
Create Date: 2026-06-12 18:00:07.613832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea48c4fe03d'
down_revision: Union[str, Sequence[str], None] = '8d673165ccf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('season_bonus_signs', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('season_bonus_exacts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('season_bonus_tabellone', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', name='uq_profile_player_season')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_season_profiles')
    # ### end Alembic commands ###
